# Generated by Django 4.2.30 on 2026-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vendor_name',
            field=models.CharField(default='Infra Supplies Pvt Ltd', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(default='Infra Supplies Pvt Ltd', max_length=255),
        ),
    ]
