# Generated by Django 4.2.30 on 2026-06-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_id', models.CharField(max_length=50)),
                ('tax_rate', models.FloatField(default=18.0)),
                ('validity', models.CharField(default='30 Days', max_length=100)),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='Submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_days', models.IntegerField(default=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.quotation')),
            ],
        ),
    ]
