# Generated by Django 4.2.30 on 2026-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('gst_no', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
            ],
        ),
    ]
