# Generated by Django 4.2.30 on 2026-06-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Construction', 'Construction'), ('Furniture', 'Furniture'), ('Logistics', 'Logistics'), ('Raw Materials', 'Raw Materials'), ('Office Supplies', 'Office Supplies'), ('Other', 'Other')], default='Other', max_length=255)),
                ('gst_no', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Links this vendor profile to a login user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
