# Generated by Django 4.2.30 on 2026-06-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Approved', 'Approved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('assigned_vendors', models.ManyToManyField(blank=True, related_name='assigned_rfqs', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RFQLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(default='NOS', max_length=50)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='rfqs.rfq')),
            ],
        ),
    ]
