# Generated by Django 4.2.30 on 2026-06-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Approved', 'Approved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_vendors', models.ManyToManyField(blank=True, related_name='assigned_rfqs', to='vendors.vendor')),
                ('created_by', models.ForeignKey(blank=True, help_text='The Procurement Officer who created this RFQ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFQLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(default='NOS', max_length=50)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='rfqs.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_days', models.PositiveIntegerField()),
                ('vendor_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfqs.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='vendors.vendor')),
            ],
        ),
    ]
