# Generated by Django 4.2.30 on 2026-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='accepted_vendors',
            field=models.ManyToManyField(blank=True, related_name='accepted_rfqs', to='vendors.vendor'),
        ),
    ]
